<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Automacao_PC" name="br.com.caelum.leilao.test.UsuariosWSTest" tests="8" failures="1" timestamp="29 Jan 2017 23:26:44 GMT" time="5.117" errors="0">
  <testcase name="deveaDeletarLeilaoXML" time="0.250" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveRetornarObjetoDeUsuariosJSON" time="0.109" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveRetornarListaDeUsuariosXML" time="3.510" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveRetornarObjetoDeUsuariosXML" time="0.172" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveRetornarObjetoDeLeilaoJSON" time="0.749" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveRetornarQuantidadeDeLeilaoJSON" time="0.109" classname="br.com.caelum.leilao.test.UsuariosWSTest">
    <failure type="java.lang.AssertionError" message="expected [6] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [8]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at br.com.caelum.leilao.test.UsuariosWSTest.deveRetornarQuantidadeDeLeilaoJSON(UsuariosWSTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- deveRetornarQuantidadeDeLeilaoJSON -->
  <testcase name="deveaDeletarUsuarioXML" time="0.156" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
  <testcase name="deveadicionarUsuarioXML" time="0.062" classname="br.com.caelum.leilao.test.UsuariosWSTest"/>
</testsuite> <!-- br.com.caelum.leilao.test.UsuariosWSTest -->
